name: CI
on:
  push:
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Netbox git tags
        netbox-version:
          - v3.2.2
          - v3.3.2
          - v3.4.4
          - v3.5.3
          - v3.6.7
          - v3.7.0
          - master

    steps:
      - uses: actions/checkout@v2
      - uses: wagoid/commitlint-github-action@v5

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$

      - name: Install Dependencies using Poetry
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build test images
        run: |
          poetry run invoke build

      - name: Run tests
        run: |
          poetry run invoke tests
