name: CI
on: [push]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Netbox git tags
        netbox-version:
          - v2.11.11
          - v3.0.8
          - master

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$

      - name: Install Dependencies using Poetry
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build test image
        run: poetry run invoke build

      - name: Run tests
        run: poetry run invoke tests
